v0.5 ModuleSystem
RedGear-Studio/RedGear-client pull request #1
Opened 2022-09-30 12:53 UTC by Gipson62

La version arrive dans +/- une semaine, la PR n'est là que pour corriger les erreurs pour merge et vérifier avec les autres si elle contient ou non toutes les features attendues.

/!\ À ne pas merge tant que tous les reviewers n'ont pas validés

2022-09-30 19:31 UTC, quentin72000 commented on Client/Client.cs
> +                    return new VerifySystem.SuccessSystem.OkSuccess("hehe", "Content");
A modifié pour mettre un vrai message

2022-09-30 20:12 UTC, quentin72000 requested changes
Le fichier utilities/Save/account_information.save ne devrait-il pas être ajouté au .gitignore ?

Sinon plutôt propre a part 1 ou 2 oublie et 1 ou 2 noms de variable pas terrible x)

2022-09-30 20:12 UTC, quentin72000 commented on Client/Client.cs
> +                    return new VerifySystem.SuccessSystem.OkSuccess("hehe", "Content");
```suggestion
                    return new VerifySystem.SuccessSystem.OkSuccess("Succes", "Content");
```
A modifié pour mettre un vrai message

2022-09-30 20:12 UTC, quentin72000 commented on Client/Client.cs
> +                    return new VerifySystem.ErrorSystem.BadRequestError("jsp", e.Message);
```suggestion
                    return new VerifySystem.ErrorSystem.BadRequestError("Bad request error / Something bad happened", e.Message);
```
Pareil, à modifier pour plus de lisiblité

2022-09-30 20:21 UTC, Gipson62 commented on Client/ClientSystem/NetworkSystem.cs
> +                string URL = "ws://83.150.217.31:2025";
Je fais ça demain !

2022-09-30 20:21 UTC, Gipson62 commented on Client/ClientSystem/NetworkSystem.cs
> +                    ClientWebSocket salut = new ClientWebSocket();
Le nom des variables sera changé demain aussi

2022-09-30 20:23 UTC, Gipson62 commented on Hehe.cs
> +using Godot;
C'est en effet plutot nécessaire vu que c'est le namespace de Godot et ducoup ça permet d'accéder à tt le reste

2022-09-30 20:24 UTC, quentin72000 commented on Hehe.cs
> +using Godot;
Faudrait t'il donc pas le nommé Godot ou Main ?

2022-09-30 20:24 UTC, Gipson62 commented on Stamina-client.csproj
> +<Project Sdk="Godot.NET.Sdk/4.0.0-beta1">
ui je sais, mais atta

2022-09-30 20:26 UTC, quentin72000 commented on README.md
> +<h3 align="center">Stamina Server</h3>
Et j'avais pas vu mais c'est Client et non Server ^^'
```suggestion
<h3 align="center">ReadGear Server</h3>
```

2022-10-01 10:28 UTC, Gipson62 commented on Hehe.cs
> +using Godot;
Tu parlais du fichier ou pas ? Parce que le using est obligatoire oui, mais sinon, Hehe.cs était juste la pour que je test un truc

2022-10-01 10:50 UTC, quentin72000 commented on Hehe.cs
> +using Godot;
Ahah non je parle bien du fichier sorry x) J'ai pas trouver la fonction pour commenter tout un fichier ducoup j'ai commenté la premiére ligne ^^'

2022-10-01 10:50 UTC, Gipson62 commented on Hehe.cs
> +using Godot;
aaaaaah, oke oke, bah c'était juste pour contourner le bug que j'avais lors du chargement du fichier Loader.cs

2022-10-03 11:11 UTC, Gamers-geek commented
Pour le code d'erreur 69, t'as pas un équivalent dans les  [code HTTP](https://fr.wikipedia.org/wiki/Liste_des_codes_HTTP) ?

2022-10-03 11:27 UTC, Gipson62 commented
> Pour le code d'erreur 69, t'as pas un équivalent dans les  [code HTTP](https://fr.wikipedia.org/wiki/Liste_des_codes_HTTP) ?

Alors, en vrai j'en ai aucune idée, je sais pas si il y a une erreur "de base" en http, mais si il y a, je suis preneur. Je me suis pas vraiment documenté la dessus

2022-10-04 13:26 UTC, Gamers-geek requested changes
Code 500 au lieu du code 69 dans Verify.cs ?

2022-10-06 17:34 UTC, Gipson62 commented
> Code 500 au lieu du code 69 dans Verify.cs ?

Je fais ça durant la semaine prochaine, au final la version prendra plus de temps, mais je compte faire une restructuration en différentes dll des différents systèmes qui seront utilisés, via des dll et via des "couches". Je vais aussi essayer de setup pour la prochaine version un système de bdd pour créer une authentification rapide et mettre en place un Github Actions pour auto compiler les différentes dll pour vérifier s'il y a des erreurs et déjà prévoir les releases. Je vais essayer de séparer en un maximum de dll car ça permettra d'utiliser le projet directement dans Godot sans réelle modification.

2022-10-09 13:14 UTC, Gipson62 commented
Je ferme la PR, car on change d'idées, mais je conserve les changements sur mon pc parce qu'ils pourraient être utiles pour plus tard.

2022-10-09 13:14 UTC, closed without merging